# Nombre de la tarea
name: Testing

# En que acción se realiza
on:
    push:
        branches:
          - main

#  Tareas a ejecutar
jobs:
  test-project:
    # En que sistema se ejecutará
    runs-on: ubuntu-latest

    # Pasos de la tarea
    steps:
      # Revisando el repositorio
      - name: Checkout repository
        uses: actions/checkout@v2
      
      # Instalar python
      - name: Set up python
        uses: actions/setup-python@v2
        with:
            python-version: 3.x

      # Instalar las dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Ejecutar las pruebas
      - name: Run Django unit tests
        run: |
          python manage.py test
